/// ═════════════════════════════════════════════════════════════
/// AUTO-GENERATED by BotForge — DO NOT EDIT MANUALLY
/// Organisation: Lux Cars (08bcf535-de76-4576-9294-2823b21b20aa)
/// Generated: 2026-05-04T14:23:21.333Z
/// Chatbot ID: e2583e4c-7659-420b-a650-1cc027cde8fb
/// ═════════════════════════════════════════════════════════════
library;

class AppConfig {
  AppConfig._();

  // ── Brand Identity ──────────────────────────────────────────────
  static const String businessName   = 'Lux Cars';
  static const String tagline        = '';
  static const String botName        = 'Lux';
  static const String botRole        = 'Customer Experience Assistant';
  static const String welcomeMessage = 'Hi there! 👋 I\'m $botName, your personal assistant at $businessName. How can I help you today?';

  static const List<String> quickReplies = [
    '💰 Pricing & Plans',
    '🛠️ Our Services',
    '📞 Contact Support'
  ];

  // ── Visuals ──────────────────────────────────────────────────────
  static const String primaryColorHex = '#e85518';
  static const String accentColorHex  = '#0f172a';
  static const String botAvatarAsset  = 'assets/images/bot_avatar.png';
  static const String logoAsset       = 'assets/images/logo.png';

  // ── Backend ──────────────────────────────────────────────────────
  static const String apiBaseUrl     = 'https://api.botforge.app';
  static const String chatEndpoint   = '/chatbots/mobile';
  static const String organisationId = '08bcf535-de76-4576-9294-2823b21b20aa';
  static const String chatbotId = 'e2583e4c-7659-420b-a650-1cc027cde8fb';
  static const String botCreatorUrl = 'https://botcreator-1.onrender.com';
  static const String apiKey = '';

  // ── Chat Session ────────────────────────────────────────────────
  static const String chatId = '';  // Generated on first chat

  // ── Business Hours ───────────────────────────────────────────────
  static const bool   showBusinessHours = false;
  static const String businessHours     = '';
  static const String offlineMessage    =
      'We are currently outside business hours. I will still do my best to help, '
      'but a human agent will follow up. 🌙';

  // ── Social / Contact ─────────────────────────────────────────────
  static const String whatsappNumber  = '';
  static const String telegramHandle  = '';
  static const String supportEmail    = '';
  static const String websiteUrl      = '';

  // ── Feature Flags ─────────────────────────────────────────────────
  static const bool enableFileAttachments = true;
  static const bool enableVoiceMessages   = false;
  static const bool enableRatings         = true;
  static const bool enableTypingIndicator = true;
  static const bool enableReadReceipts    = true;
}